export default {
    name: "HC zDPS Melee League (PL7491)",
    ignoreCharactersBelowLevel: 10,
    rules: {
        influence: {
            enabled: false,
            display: "Item Influence",
            mode: "blacklist",
            list: [],
        },
        gem: {
            threshold: 5,
            enabled: true,
            display: "Gems",
            mode: "whitelist",
            list: [
                "Ancestral Warchief",
                "Ancestral Protector",
                "Blade Flurry",
                "Bladestorm",
                "Chain Hook",
                "Charged Dash",
                "Cleave",
                "Consecrated Path",
                "Doryani's Touch",
                "Double Strike",
                "Vaal Lightning Strike",
                "Vaal Double Strike",
                "Frost Bomb",
                "Dual Strike",
                "Earthquake",
                "Flicker Strike",
                "Frost Blades",
                "Glacial Hammer",
                "Ground Slam",
                "Heavy Strike",
                "Ice Crash",
                "Infernal Blow",
                "Lacerate",
                "Leap Slam",
                "Lightning Strike",
                "Molten Strike",
                "Perforate",
                "Pestilent Strike",
                "Puncture",
                "Reave",
                "Reckoning",
                "Riposte",
                "Shield Charge",
                "Smite",
                "Static Strike",
                "Sunder",
                "Sweep",
                "Tectonic Slam",
                "Vengeance",
                "Vigilant Strike",
                "Viper Strike",
                "Whirling Blades",
                "Wild Strike",
                "Elemental Hit",
                "Frenzy",
                "Purity of Elements",
                "Discipline",
                "Vaal Discipline",
                "Wrath",
                "Clarity",
                "Vaal Clarity",
                "Icicle Mine",
                "Purity of Lightning",
                "Vaal Impurity of Lightning",
                "Zealotry",
                "Malevolence",
                "Stormblast Mine",
                "Summon Skitterbots",
                "Vitality",
                "Determination",
                "Anger",
                "Rejuvenation Totem",
                "Purity of Fire",
                "Vaal Impurity of Fire",
                "War Banner",
                "Dread Banner",
                "Flesh and Stone",
                "Pride",
                "Haste",
                "Vaal Haste",
                "Grace",
                "Vaal Grace",
                "Hatred",
                "Purity of Ice",
                "Vaal Impurity of Ice",
                "Precision",
                "Summon Chaos Golem",
                "Summon Lightning Golem",
                "Summon Carrion Golem",
                "Summon Flame Golem",
                "Summon Stone Golem",
                "Summon Ice Golem",
                "Immortal Call",
                "Molten Shell",
                "Vaal Molten Shell",
                "Animate Guardian",
                "Steelskin",
                "Enduring Cry",
                "Rallying Cry",
                "Abyssal Cry",
                "Decoy Totem",
                "Elemental Weakness",
                "Enfeeble",
                "Assassin's Mark",
                "Despair",
                "Flammability",
                "Frostbite",
                "Conductivity",
                "Bane",
                "Warlord's Mark",
                "Punishment",
                "Vulnerability",
                "Temporal Chains",
                "Projectile Weakness",
                "Poacher's Mark",
                "Lightning Warp",
                "Flame Dash",
                "Frostblink",
                "Phase Run",
                "Smoke Mine",
                "Blink Arrow",
                "Mirror Arrow",
                "Dash",
                "Withering Step",
                "Tempest Shield",
                "Herald of Thunder",
                "Herald of Ash",
                "Herald of Ice",
                "Added Fire Damage Support",
                "Inspiration Support",
                "Knockback Support",
                "Life Leech Support",
                "Stun Support",
                "Melee Physical Damage Support",
                "Increased Duration Support",
                "Cold to Fire Support",
                "Elemental Damage with Attacks Support",
                "Bloodlust Support",
                "Life Gain on Hit Support",
                "Blood Magic Support",
                "Iron Grip Support",
                "Iron Will Support",
                "Damage on Full Life Support",
                "Spell Totem Support",
                "Ballista Totem Support",
                "Fire Penetration Support",
                "Multistrike Support",
                "Melee Splash Support",
                "Burning Damage Support",
                "Cast on Melee Kill Support",
                "Empower Support",
                "Endurance Charge on Melee Stun Support",
                "Less Duration Support",
                "Cast when Damage Taken Support",
                "Generosity Support",
                "Fortify Support",
                "Chance to Bleed Support",
                "Maim Support",
                "Brutality Support",
                "Ruthless Support",
                "Ancestral Call Support",
                "Multiple Totems Support",
                "Shockwave Support",
                "Pulverise Support",
                "Rage Support",
                "Faster Attacks Support",
                "Greater Multiple Projectiles Support",
                "Lesser Multiple Projectiles Support",
                "Greater Volley Support",
                "Faster Projectiles Support",
                "Added Cold Damage Support",
                "Additional Accuracy Support",
                "Mana Leech Support",
                "Pierce Support",
                "Trap Support",
                "Culling Strike Support",
                "Point Blank Support",
                "Chance to Flee Support",
                "Blind Support",
                "Cold Penetration Support",
                "Chain Support",
                "Fork Support",
                "Cast On Critical Strike Support",
                "Multiple Traps Support",
                "Slower Projectiles Support",
                "Cast on Death Support",
                "Enhance Support",
                "Vicious Projectiles Support",
                "Block Chance Reduction Support",
                "Ice Bite Support",
                "Hypothermia Support",
                "Trap and Mine Damage Support",
                "Poison Support",
                "Void Manipulation Support",
                "Swift Affliction Support",
                "Cluster Traps Support",
                "Advanced Traps Support",
                "Lesser Poison Support",
                "Deadly Ailments Support",
                "Vile Toxins Support",
                "Onslaught Support",
                "Herald of Purity",
                "Herald of Agony",
                "Blood and Sand",
                "Blood Rage",
                "Volley Support",
                "Mirage Archer Support",
                "Charged Traps Support",
                "Withering Touch Support",
                "Close Combat Support",
                "Vaal Ground Slam",
                "Impale Support",
                "Vaal Glacial Hammer",
                "Shockwave",
                "Vaal Reave",
                "Vaal Earthquake",
                "Vaal Ancestral Warchief",
                "Nightblade Support",
                "Swift Assembly Support",
                "Arrow Nova Support",
                "Barrage Support",
                "Increased Area of Effect Support",
                "Added Lightning Damage Support",
                "Increased Critical Strikes Support",
                "Increased Critical Damage Support",
                "Added Chaos Damage Support",
                "Item Rarity Support",
                "Faster Casting Support",
                "Concentrated Effect Support",
                "Minion Damage Support",
                "Combustion Support",
                "Minion Speed Support",
                "Minion Life Support",
                "Elemental Proliferation Support",
                "Blastchain Mine Support",
                "Lightning Penetration Support",
                "Spell Echo Support",
                "Power Charge On Critical Support",
                "Elemental Army Support",
                "Curse On Hit Support",
                "Cast when Stunned Support",
                "Enlighten Support",
                "Physical to Lightning Support",
                "Blasphemy Support",
                "Innervate Support",
                "Controlled Destruction Support",
                "Elemental Focus Support",
                "Minefield Support",
                "Cast while Channelling Support",
                "Ignite Proliferation Support",
                "Decay Support",
                "Efficacy Support",
                "Immolate Support",
                "Unbound Ailments Support",
                "Arcane Surge Support",
                "Infused Channelling Support",
                "Spell Cascade Support",
                "Summon Phantasm Support",
                "Charged Mines Support",
                "Bonechill Support",
                "Energy Leech Support",
                "Intensify Support",
                "Unleash Support",
                "Feeding Frenzy Support",
                "Deathmark Support",
                "Meat Shield Support",
                "Berserk",
                "Arctic Armour",
                "High-Impact Mine Support",
                "Infernal Legion Support",
                "Plague Bearer",
                "Portal",
            ],
        },
        class: {
            enabled: false,
            display: "Character Class",
            mode: "blacklist",
            list: [],
        },
        passive: {
            enabled: false,
            display: "Passive Skills",
            mode: "blacklist",
            list: [],
        },
        jewelRarity: {
            enabled: false,
            display: "Jewel Rarity",
            mode: "blacklist",
            list: [],
        },
        itemRarity: {
            enabled: false,
            display: "Item Rarity",
            mode: "blacklist",
            list: [],
        },
        flaskRarity: {
            enabled: false,
            display: "Flask Rarity",
            mode: "blacklist",
            list: [],
        },
        unique: {
            enabled: false,
            display: "Unique Items",
            mode: "blacklist",
            list: [],
        },
        linkedGem: {
            enabled: true,
            display: "Linked Gems",
            mode: "blacklist",
            list: ["Herald of Agony", "Herald of Purity"],
        },
        abyssJewelRarity: {
            enabled: false,
            display: "Abyss Jewel Rarity",
            mode: "blacklist",
            list: [],
        },
    },
};
