export enum RuleId {
    Gem = "gem",
    Unique = "unique",
    Class = "class",
    Influence = "influence",
    JewelRarity = "jewelRarity",
    NoPrivateProfile = "noPrivateProfile",
    Passive = "passive",
    FlaskRarity = "flaskRarity",
    ItemRarity = "itemRarity",
    LinkedGem = "linkedGem",
    AbyssJewelRarity = "abyssJewelRarity",
    Affix = "affix",
    Corrupted = "corrupted",
}
